name: quizdb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.0
  sqflite: ^2.4.0
  path_provider: ^2.1.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "images/logo.png"
    icon_size: 48

flutter:
  uses-material-design: true
  assets:
    - images/starting.png
    - images/choose.png
    - images/lightbulb.png
    - images/algorithm.png
    - images/database.png
    - images/1.png
    - images/Flutter.png
    - images/HTML.png
    - images/SQL.png
    - images/C++.png
    - images/correct.png
    - images/starting.png
    - images/logo.png